# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'PerfectBCryptDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PerfectBCryptDemo
  pod 'BCrypt'
end
